from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
REPORTS_DIR = ROOT / "reports"
PLOTS_DIR = REPORTS_DIR / "plots"


@dataclass(slots=True)
class Settings:
    brands: list[str] = field(
        default_factory=lambda: [
            "Supreme",
            "Rick Owens",
            "Stone Island",
            "Comme des Garcons",
            "Our Legacy",
            "Maison Margiela",
            "Acne Studios",
            "Aimé Leon Dore",
            "Alexander McQueen",
            "Amiri",
            "Alyx",
            "Arc'teryx",
            "Balenciaga",
            "Balmain",
            "BAPE",
            "Bode",
            "Boramy Viguier",
            "Bottega Veneta",
            "Brunello Cucinelli",
            "Burberry",
            "C.P. Company",
            "Canada Goose",
            "Carhartt WIP",
            "Cav Empt",
            "Celine",
            "Chrome Hearts",
            "Craig Green",
            "Daiwa Pier39",
            "Dries Van Noten",
            "Engineered Garments",
            "Erdem",
            "Essentials",
            "Fear of God",
            "Fendi",
            "Givenchy",
            "Guidi",
            "Helmut Lang",
            "Human Made",
            "Isabel Marant",
            "Issey Miyake",
            "Jacquemus",
            "Jean Paul Gaultier",
            "Jil Sander",
            "Junya Watanabe",
            "Kapital",
            "Kiko Kostadinov",
            "Lanvin",
            "Lemaire",
            "Louis Vuitton",
            "Maison Mihara Yasuhiro",
            "Marine Serre",
            "Marni",
            "Moncler",
            "Needles",
            "Neighborhood",
            "New Balance",
            "Noah",
            "Number (N)ine",
            "Off-White",
            "OAMC",
            "Palace",
            "Prada",
            "Raf Simons",
            "Red Wing",
            "Reigning Champ",
            "Represent",
            "Roa",
            "Sacai",
            "Salomon",
            "Sandy Liang",
            "Sasquatchfabrix",
            "Stella McCartney",
            "Stussy",
            "Sunnei",
            "Takahiromiyashita TheSoloist",
            "The North Face",
            "Thom Browne",
            "Tom Ford",
            "Undercover",
            "Uniqlo",
            "Vejas",
            "VETEMENTS",
            "Visvim",
            "Wacko Maria",
            "Wales Bonner",
            "Y-3",
            "Y/Project",
            "Yeezy",
            "Yohji Yamamoto",
            "A.P.C.",
            "And Wander",
            "Auralee",
            "Barbour",
            "Beams Plus",
            "Common Projects",
            "Danner",
            "Evisu",
            "Filson",
            "Golden Goose",
            "Hoka",
            "John Elliott",
            "Kith",
            "Mackage",
